services:
  traefik:
    image: traefik:v2.10
    container_name: traefik-proxy
    ports:
      - "8000:80"
      - "8080:8080"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"

  backend:
    build:
      context: ./backend
      args:
        GO_VERSION: ${GO_VERSION}
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        APP_VERSION: ${APP_VERSION:-dev}
        GIT_COMMIT: ${GIT_COMMIT:-local}
        BUILD_DATE: ${BUILD_DATE:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}
    container_name: go-backend
    env_file:
      - .env
    expose: 
      - "8080"
    ports:
      - "8080:8080" 
    working_dir: /app
    volumes:
      - backend_data:/app/data
    labels:
      - "traefik.enable=true"  # Enable Traefik for this service
      
      # Route: from /api to backend
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      
      # Service: define backend service and port
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend

  frontend:
    build:
      context: ./frontend
      args:
        NODE_VERSION: ${NODE_VERSION}
        NGINX_VERSION: ${NGINX_VERSION}
    container_name: vue-frontend
    env_file:
      - .env
    expose:
      - "80"
    working_dir: /app
    labels:
      - "traefik.enable=true"
      
      # Route: everything that is not /api to frontend
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.priority=1"
      
      # Service
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend

volumes:
  backend_data:
    driver: local