name: Terraform Validate

on:
  pull_request:
    paths:
      - 'terraform/environments/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VERSION: 1.9.5
  TERRAFORM_WORKING_DIR: 'terraform/environments/prod'

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform FMT
        id: fmt
        run: |
          changes=$(terraform fmt -recursive -check || echo "true")
          if [ "$changes" = "true" ]; then
            terraform fmt -recursive
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit formatted files
        if: steps.fmt.outputs.changes_detected == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "style: Auto-format Terraform files"
          git push

      - name: Terraform Baisc Actions (Init, Validate, Plan)
        uses: ./.github/workflows/actions/terraform-init-validate-plan.yaml
        with:
          working_directory: ${{ env.TERRAFORM_WORKING_DIR }}

      - name: Comment PR with Plan
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ${{ env.TERRAFORM_WORKING_DIR }}/plan.out
          message: |
            ### Terraform Plan result
            ```
            ${{ steps.plan.outputs.stdout }}
            ```
